module: KituraMustache
author: IBM
github_url: https://github.com/IBM-Swift/Kitura-MustacheTemplateEngine/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, KituraMustache.xcodeproj, -target, KituraMustache, LIBRARY_SEARCH_PATHS=.build/debug]

